frequency-chain/provider-dashboard

- package-lock.json
- package.json
- src/components/Hello.svelte
- src/routes/+page.svelte
- test/__snapshots__/hello.test.ts.snap
- test/hello.test.ts
- vitest.config.ts
Uses the recommended testing frameworks with Svelte, includes a Hello component with a hello.test, uses Typescript.  
Closes #3 
With @mattheworris
> Feat/jest testing #3

- src/components/Connect.svelte
- src/components/Hello.svelte
- src/routes/+page.svelte
Implement the selection and connection to a network.
Closes #2
> feat: Select and connect to a network

- package-lock.json
- src/lib/connections.ts
- test/lib/connections.test.ts
- tsconfig.json
@mattheworris and I agreed to merge this mocking work so he can use it and I will continue to write some more tests for the `connections.ts` functions
> Unit tests

- README.md
- package-lock.json
- package.json
- src/components/Connect.svelte
- src/lib/connections.ts
- src/lib/polkadotApi.ts
- src/lib/stores.ts
- src/routes/+page.svelte
- test/connect.test.ts
- test/page.test.ts
- tsconfig.json
- vite.config.ts
- vitest.config.ts
Initial basis for e2e testing, mostly refactoring Connect.svelte and fixing TS errors.
> E2e testing

- src/components/Connect.svelte
- test/page.test.ts
Show a link to the Frequency Rococo Faucet when connection to Rococo.
> Faucet link

- src/components/Capacity.svelte
- src/components/Connect.svelte
- src/components/Intro.svelte
- src/lib/connections.ts
- src/routes/+page.svelte
- static/app.css
- test/components/capacity.test.ts
- test/components/connect.test.ts
- test/components/intro.test.ts
- test/page.test.ts
Add some explaining text.  Closes #22 and Closes #23 
* feat: add viewable and dismissable explainer text for choosing a network
* feat: add dismissable intro text before showing network choices
* fix: remove leftover console log
https://github.com/LibertyDSNP/provider-dashboard/assets/502640/a209c8fb-a65d-48f8-b83e-331d0e4c7536
> Lucy, you have some explaining to do

- README.md
- svelte.config.js
We are all of a sudden getting deploy failures; locally this seems to fix the issue.
Also use a status badge on the README.
> fix deployment

- .gitignore
- src/components/AddControlKey.svelte
- src/components/Banner.svelte
- src/components/Capacity.svelte
- src/components/ChainStatus.svelte
- src/components/Connect.svelte
- src/components/Intro.svelte
- src/components/Provider.svelte
- src/components/Stake.svelte
- src/components/TransactionStatus.svelte
- src/style/app.css
- tailwind.config.js
- added new colors
- removed old colors
- formatting applied
- closes #63
> added colors to theme

- src/components/AddControlKey.svelte
- src/components/CreateMsa.svelte
- src/components/CreateProvider.svelte
- src/components/RequestToBeProvider.svelte
- src/components/Stake.svelte
- src/style/app.css
- tailwind.config.js
closes #65 
- redefines button classes
- needed to update typography sizes to get this right so added that even though jumping ahead
- remove unused code
> redefine button classes

- src/style/app.css
- tailwind.config.js
> defined typeography

- src/components/Nav.svelte
- src/routes/+layout.svelte
Hot fix for #70
Problem: was not position: fixed.
> hot fix. Nav not fixed

- src/components/Connect.svelte
- src/components/KeySelection.svelte
- src/lib/polkadotApi.ts
- src/lib/stores.ts
- src/routes/+page.svelte
- src/style/app.css
- test/e2e/page.test.ts
> only above to select from provider accounts. provider accounts now saved in store.

- src/components/ActivityLogPreview.svelte
- src/components/Dashboard.svelte
- src/components/DashboardHeader.svelte
- src/components/KeySelection.svelte
- src/components/Profile.svelte
- src/lib/stores.ts
- src/style/app.css
closes #83 
Note: going with a lighter weight solution => https://unfinished-team.slack.com/archives/C05FC0YUP51/p1705440655948859
> Dashboard Header Section

- tsconfig.json
Fixed $libs and $components aliases in imports
> fix: import aliases

- src/components/ConnectProvider.svelte
- src/components/ConnectionStatus.svelte
- src/components/Modal.svelte
> connect provider hot fix. dropdown menu options changed

- src/components/ChainStatus.svelte
- src/components/Dashboard.svelte
- src/style/app.css
- tailwind.config.js
- test/unit-and-integration/chainStatus.test.ts
closes #84 
note: removed remaining balance (https://unfinished-team.slack.com/archives/C05FC0YUP51/p1706034815763449)
> chain status overview

- src/components/AddControlKey.svelte
- src/components/Capacity.svelte
- src/components/ChainStatus.svelte
- src/components/ConnectionStatus.svelte
- src/components/Dashboard.svelte
- src/components/Provider.svelte
- src/components/Stake.svelte
- src/lib/polkadotApi.ts
- src/lib/stores.ts
- test/unit-and-integration/capacity.test.ts
- test/unit-and-integration/chainStatus.test.ts
- test/unit-and-integration/connections.test.ts
- test/unit-and-integration/createMsa.test.ts
- test/unit-and-integration/createProvider.test.ts
- test/unit-and-integration/provider.test.ts
- test/unit-and-integration/requestToBeProvider.test.ts
- test/unit-and-integration/stake.test.ts
> remove duplicate store values

- src/components/AddControlKey.svelte
- src/components/HowToTransact.svelte
- src/components/ProviderLogin.svelte
- src/components/Stake.svelte
- src/routes/faq/+page.svelte
- src/style/app.css
> create reusable component for how to transact. add reusable styling.

- src/components/ActivityLogPreview.svelte
- src/components/AddControlKey.svelte
- src/components/BecomeAProvider.svelte
- src/components/Stake.svelte
- src/components/StakeForm.svelte
- src/components/TransactionStatus.svelte
- src/lib/storeTypes.ts
- src/lib/stores.ts
- src/style/app.css
- test/unit-and-integration/provider.test.ts
closes #151 
- Start using 350px everywhere instead of some 350 and some 320.
- Add divider into transaction status component and remove from parent components.
- comment out activity log content.
> style updates

- test/unit-and-integration/becomeProvider.test.ts
Basic test for the `BecomeAProvider` component
> Become a provider tests

- package-lock.json
- scripts/run_e2e_tests.sh
- src/components/HowToTransact.svelte
- src/lib/stores/networksStore.ts
- src/routes/faq/+page.svelte
- test/unit-and-integration/utils.test.ts
The goal of this PR is to remove the Frequency Rococo option
> Remove the Rococo Testnet chain option

- README.md
- src/components/HowToTransact.svelte
- src/components/Nav.svelte
- src/components/NavItem.svelte
- src/components/ProviderLogin.svelte
The goal of this PR is to:
* Add links to Faucet in Nav and Login pane
* Adjust text a little to account for the changes to the login
* Fix link on README to create-svelte repo
Closes #167 
Closes #166 
2. `npm run dev`
3. Click the link for the faucet, verify it opens in a new tab
4. Connect a provider account and link the link in the sidebar for the faucet, verify it opens in a new tab
> Link updates

- src/components/BecomeAProvider.svelte
- src/components/SelectNetworkAndAccount.svelte
- src/lib/stores/accountsStore.ts
- src/lib/stores/networksStore.ts
- src/lib/utils.ts
- test/e2e/page.test.ts
The goal of this PR is to have better naming of the network dropdown.
Closes #187 
By switching to an id with an enum we get much better type safety and have a pretty name!
> Fix network selection dropdown formatting

- src/components/BackHomeButton.svelte
- src/components/BecomeAProvider.svelte
- src/components/CreateMsa.svelte
- src/components/CreateProvider.svelte
- src/components/RequestToBeProvider.svelte
- test/unit-and-integration/requestToBeProvider.test.ts
The goal of this PR is to request to become to a provider using the proppose to be a provider extrinsic.
Closes #205 
- repurpose request to be a provider component
- improve logging
- [na] Docs updated
- [na] Tests added
2. Run through the mainnet request to become provider flow if you have FRQY in your account
3. If not, change the condition in `BecomeAProvider` to testnet and run the mock flow through testnet
4. Run success cases (has enough tokens, etc.)
5. Run failure cases (has already submitted a request, etc.)
pt.1
https://github.com/user-attachments/assets/bdf7aa31-d464-4ef9-8682-6a8d83f147ca
pt.2
https://github.com/user-attachments/assets/bc7d7528-a7e1-488c-8fd2-b659811835e4
pt.3
https://github.com/user-attachments/assets/2a770202-12fb-4384-a7bf-157acef4771 …
> request to be a provider

- src/components/BecomeAProvider.svelte
Accidentally didn't change Testnet back to Mainnet when I was finished testing.
> remove mainnet test code

- src/components/DropDownMenu.svelte
- src/components/SelectNetworkAndAccount.svelte
- src/lib/assets/LoadingIcon.svelte
The goal of this PR is to add a spinner while connecting to a network
Closes #115 
- adjust styling to take this into account
- check to see if changes to the icon ruin any other styling
2. ...
https://github.com/user-attachments/assets/1e9a8e28-3310-4a26-8807-cf7e3cbc8b9e
> add loading icon to select network and account

- src/components/features/Capacity/Capacity.svelte
- src/components/features/Capacity/Unstake.svelte
- src/components/features/Capacity/UnstakeForm.svelte
- src/lib/connections.ts
The goal of this PR is to be able to unstake
Closes #185 
- Do we want to add anything to the requirements section? Is what's there now valid?
- **Thought for new ticket**: Add a toast that lets the user know what value will be changing after their action. Example: after stake, the value for locked should increase.
2. test numbers update as expected for stake and unstake
> add unstaking form

- src/components/features/Capacity/UnstakeForm.svelte
- src/components/features/LoginForm/LoginForm.svelte
- src/components/features/Provider/AddControlKeyForm.svelte
- src/components/features/SelectNetworkAndAccount/SelectNetworkAndAccount.svelte
- src/components/pages/Dashboard.svelte
- src/lib/polkadotApi.ts
- src/lib/stores/accountsStore.ts
- src/lib/utils.ts
- src/routes/+layout.svelte
The goal of this PR is to have the stores automatically update when a new account is added.
Closes #245 
- on add to account, the store is updates and you should instantly see it in the dropdown.
- the extension does not support updating the list on removal of an account. you will have to refresh to see that update.
2. add and remove connected accounts from polkadot extension
3. see the dropdowns react in real time
> when a new account is added, stores automatically update

- src/components/features/NoExtensionError.svelte
- src/components/features/SelectNetworkAndAccount/SelectAccount.svelte
- test/e2e/NoExtensionError.test.ts
The goal of this PR is to get 100% coverage on the NoExtensionError file
Part of #261 
- added tests
- ran prettier
- added id to make sure i was looking at the right thing.
1. Run test
2. make sure coverage is at 100%
> add tests for no extension error

- src/components/features/BecomeProviderNextSteps/CreateProvider.svelte
- src/lib/assets/LoadingIcon.svelte
- src/lib/connections.ts
- test/e2e/CreateProvider.test.ts
- test/helpers.ts
The goal of this PR is to get full coverage for create provider
part of #261 
- achieved full coverage of the test suite
2. run coverage
3. see tests pass and full coverage in create provider
> Create provider test coverage

- test/unit-and-integration/utils.test.ts
The goal of this PR is to have full coverage on utils
part of #261 
- achieved full coverage
2. run coverage
3. see 100% on utils
> full coverage on utils

- package-lock.json
- package.json
- src/components/features/Capacity/StakeForm.svelte
- src/components/features/Capacity/UnstakeForm.svelte
- src/components/features/LoginForm/LoginForm.svelte
- src/components/features/ProfileOverview/Profile.svelte
- src/components/features/Provider/AddControlKey.svelte
- src/components/features/Provider/AddControlKeyForm.svelte
- src/components/features/SelectNetworkAndAccount/SelectAccount.svelte
- src/components/features/SelectNetworkAndAccount/SelectNetwork.svelte
- src/components/features/SelectNetworkAndAccount/SelectNetworkAndAccount.svelte
- src/components/pages/Dashboard.svelte
- src/lib/connections.ts
- src/lib/stores/accountsStore.ts
- src/lib/utils.ts
- src/routes/+layout.svelte
- src/routes/faq/+page.svelte
- test/e2e/Dashboard.test.ts
- test/e2e/LoginForm.test.ts
- test/e2e/SelectNetwork.test.ts
- test/e2e/SelectNetworkAndAccount.test.ts
- test/e2e/StakeForm.test.ts
- test/e2e/page.test.ts
- test/unit-and-integration/faq.test.ts
- test/unit-and-integration/stake.test.ts
- test/unit-and-integration/utils.test.ts
The goal of this PR is to update the components to work with the style guide upgrade on bits ui and shadcn.
- Due to updating the components and their new functionality, some logic changes had to be made, specifically around the sign in/switch account form.
- Due to the update, some tests are now broken. Commented them out due to time-boxing the issue and not being able to resolve.
- the upgrade caused breaking changes, calling for this level of an upgrade
2. QA the functionality of all forms
3. QA the login/logout/switch account logic
4. make sure to reload pages and see state as expected
5. QA error messages on forms (cancel the transaction / not enough funds)
> Upgrade bits UI
